apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend00-prod

resources:
- namespace.yaml
- deploy-canary.yaml
- dest-rules-canary.yaml

configMapGenerator:
- name: backend00-config
  literals:
  - ENV=canary

patches:
- target:
    kind: Service
    name: backend00
  path: patch-service.yaml
