# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: backend00
  annotations:
    about: This is a simple Go backend
  labels:
    lang: golang
description: |
  Delivery pipeline for CI CD app/Bakend (in go).
serialPipeline:
  stages:
  - targetId: dev
    profiles: [dev]
  - targetId: canary
    profiles: [canary]
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: 01 Development cluster (internal, autopush, integration tests)
gke:
  cluster: projects/prj-kokiri-dev/locations/us-central1-c/clusters/gke-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: canary
description: 02 canary to prod cluster (test release 90/10 to new release).
gke:
<<<<<<< HEAD
  cluster: projects/prj-kokiri-dev/locations//clusters/
=======
  cluster: projects/prj-kokiri-dev/locations/us-central1-c/clusters/gke-prod-asm
>>>>>>> eb25ddc (first commit to csr)
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: 03 prod cluster (external, as stable as it can be).
requireApproval: true
gke:
<<<<<<< HEAD
  cluster: projects/prj-kokiri-dev/locations//clusters/
=======
  cluster: projects/prj-kokiri-dev/locations/us-central1-c/clusters/gke-prod-asm
>>>>>>> eb25ddc (first commit to csr)
