steps:
- id: 'repoBuildConfirmation'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$PROJECT_ID"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "$SHORT_SHA"
      echo "$TAG_NAME"
      echo "$LOCATION"
      echo "***********************"

- name: gcr.io/k8s-skaffold/skaffold:v2.0.5
  id: skaffoldBuild
  args:
    - 'skaffold'
    - 'build'
    - '--file-output=/workspace/artifacts.json'
    - '--profile=dev'
    - '--module=$_DEPLOY_PIPELINE'

- id: 'cloudDeployDev'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - skaffoldBuild
  args:
  - '-c'
  - |
      gcloud deploy releases create "$_DEPLOY_PIPELINE-$SHORT_SHA"  \
        --delivery-pipeline="$_DEPLOY_PIPELINE" \
        --build-artifacts=/workspace/artifacts.json \
        --skaffold-file="apps/$_DEPLOY_PIPELINE/skaffold.yaml" \
        --skaffold-version="2.0" \
        --region="$LOCATION" &&
        echo "$_DEPLOY_PIPELINE-$SHORT_SHA" > "$_RELEASE_FILE_PATH" # /workspace/.cb.releasename

- id: 'testsForDev'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  waitFor:
  - cloudDeployDev
  args:
  - '-c'
  - |
      echo "***********************"
      echo "Tests would go here"
      echo "***********************"

- name: gcr.io/k8s-skaffold/skaffold:v2.0.5
  id: skaffoldBuildRelease
  waitFor:
  - testsForDev
  args:
    - 'skaffold'
    - 'build'
    - '--file-output=/workspace/artifacts.json'
    - '--profile=prod'
    - '--module=$_DEPLOY_PIPELINE'


- id: 'cloudDeployProd'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - skaffoldBuildRelease
  args:
  - '-c'
  - |
      gcloud deploy releases promote --to-target "prod" \
        --release=$_DEPLOY_PIPELINE-$SHORT_SHA \
        --region=$LOCATION \
        --delivery-pipeline=$_DEPLOY_PIPELINE \
        --quiet

options:
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _ARTIFACT_REPO_NAME: cicd
  _RELEASE_FILE_PATH: /workspace/.cb.releasename
