steps:
- id: 'repoBuildConfirmation'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$PROJECT_ID"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "$SHORT_SHA"
      echo "$TAG_NAME"
      echo "$LOCATION"
      echo "***********************"

- name: gcr.io/k8s-skaffold/skaffold:v2.0.5
  id: skaffoldBuild
  args:
    - 'skaffold'
    - 'build'
    - '--file-output=/workspace/artifacts.json'
    - '--profile=dev'
    - '--module=$_DEPLOY_PIPELINE'

- id: 'cloudDeployDev'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - skaffoldBuild
  args:
  - '-c'
  - |
      gcloud deploy releases create "$_DEPLOY_PIPELINE-$SHORT_SHA"  \
        --delivery-pipeline="$_DEPLOY_PIPELINE" \
        --build-artifacts=/workspace/artifacts.json \
        --skaffold-file="apps/$_DEPLOY_PIPELINE/skaffold.yaml" \
        --skaffold-version="2.0" \
        --region="$LOCATION" &&
        echo "$_DEPLOY_PIPELINE-$SHORT_SHA" > "$_RELEASE_FILE_PATH"

- id: 'waitForDeployDev'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - cloudDeployDev
  args:
  - '-c'
  - |
      _STATUS="PENDING"

      echo "checking status: $_STATUS"
      while [ "$_STATUS" != "SUCCEEDED" ]; do

        _STATUS=$(gcloud deploy rollouts describe \
          $_DEPLOY_PIPELINE-$SHORT_SHA-to-canary-0001 \
          --delivery-pipeline $_DEPLOY_PIPELINE \
          --release $_DEPLOY_PIPELINE-$SHORT_SHA \
          --format "value(state)")

      done

      echo "$_STATUS"

- id: 'testsForDev'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  waitFor:
  - cloudDeployDev
  args:
  - '-c'
  - |
      echo "***********************"
      echo "Tests would go here"
      cat $_RELEASE_FILE_PATH
      echo "***********************"

- id: 'cloudDeployCanary'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - testsForDev
  args:
  - '-c'
  - |
      gcloud deploy releases promote --to-target "canary" \
        --release=$_DEPLOY_PIPELINE-$SHORT_SHA \
        --region=$LOCATION \
        --delivery-pipeline=$_DEPLOY_PIPELINE \
        --quiet

- id: 'cloudDeployProd'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - cloudDeployCanary
  args:
  - '-c'
  - |
      gcloud deploy releases promote --to-target "prod" \
        --release=$_DEPLOY_PIPELINE-$SHORT_SHA \
        --region=$LOCATION \
        --delivery-pipeline=$_DEPLOY_PIPELINE \
        --quiet

options:
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _ARTIFACT_REPO_NAME: cicd
  _RELEASE_FILE_PATH: /workspace/.cb.releasename
