apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: backend00
  annotations:
    about: This is a simple Go backend
  labels:
    lang: golang
description: |
  Delivery pipeline for CI CD app/Bakend (in go).
serialPipeline:
  stages:
  - targetId: dev
    profiles: [dev]
  - targetId: canary
    profiles: [canary]
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: 01 Development cluster (internal, autopush, integration tests)
gke:
  cluster: projects/prj-zeld-deku/locations/us-central1-c/clusters/gke-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: canary
description: 02 canary to prod cluster (test release 90/10 to new release).
gke:
  cluster: projects/prj-zeld-deku/locations/us-central1-c/clusters/gke-prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: 03 prod cluster (external, as stable as it can be).
requireApproval: true
gke:
  cluster: projects/prj-zeld-deku/locations/us-central1-c/clusters/gke-prod
