apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend00
  labels:
    name: backend00
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: backend00
  template:
    metadata:
      labels:
        name: backend00
        version: canary
    spec:
      restartPolicy: Always
      containers:
      - name: backend00
        image: us-central1-docker.pkg.dev/prj-zeld-deku/cicd/be00
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
